version: '3'

services:
  mongo:
    container_name: mongo-container
    build: 
      context: database/
    image: mongodb-image
    
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./server/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js  # Monté depuis server/
    environment:
      MONGO_USER: myUser
      MONGO_PASSWORD: myPassword
      MONGO_DB: e-com
    networks:
      - three-tier-net

  backend:
    container_name: server
    build: 
      context: server/
    image: server-image
    ports:
      - "5000:5000"
    environment:
      MONGO_USER: myUser
      MONGO_PASSWORD: myPassword
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DB: e-com 

    depends_on:
      - mongo
    volumes:
      - "./server:/app"
    networks:
      - three-tier-net

  frontend:
    container_name: client
    build: 
      context: client/
    image: client-image
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - three-tier-net

networks:
  three-tier-net:
    driver: bridge

volumes:
  mongo-data:

