# Utiliser l'image officielle de MongoDB
FROM mongo:latest

# Définir un volume pour stocker les données de MongoDB
VOLUME ["/data/db"]

# Exposer le port par défaut de MongoDB
EXPOSE 27017

# Définir la commande par défaut pour démarrer MongoDB
CMD ["mongod"]

