apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: three-tier
  name: mongo-app
  labels:
    app: mongo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-app
  template:
    metadata:
      labels:
        app: mongo-app
    spec:
      containers:
      - name: mongo-app
        image: wissem200/mongodb:2.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_USER
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_PASSWORD
        # - name: MONGO_HOST
        #   valueFrom:
        #     configMapKeyRef:
        #       name: mongo-config
        #       key: MONGO_HOST
        # - name: MONGO_PORT
        #   valueFrom:
        #     configMapKeyRef:
        #       name: mongo-config
        #       key: MONGO_PORT
        - name: MONGO_DB
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: MONGO_DB
        volumeMounts:
          - name: mongo-volume
            mountPath: /data/db
      volumes: 
      - name: mongo-volume
        persistentVolumeClaim:
          claimName: mongo-volume-claim


